# Generated by Django 5.0.4 on 2024-04-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0003_alter_pattern_featured_image_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='updated_on',
        ),
    ]
