# Generated by Django 5.0.4 on 2024-04-09 21:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0005_remove_pattern_status_alter_pattern_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dehwhmatn/image/upload/v1712673845/placeholder_pattern_y33fzt', max_length=255, verbose_name='image'),
        ),
    ]
