# Generated by Django 5.0.4 on 2024-04-10 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0007_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_patterns', to=settings.AUTH_USER_MODEL),
        ),
    ]
