# Generated by Django 5.0.4 on 2024-04-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0008_pattern_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
