# Generated by Django 5.0.4 on 2024-04-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0010_projectlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlist',
            name='patterns',
            field=models.ManyToManyField(related_name='project_lists', to='pattern.pattern'),
        ),
    ]
