# Generated by Django 5.0.4 on 2024-04-11 12:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0011_alter_projectlist_patterns'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pattern',
            old_name='difficulity_level',
            new_name='difficulty_level',
        ),
        migrations.AddField(
            model_name='pattern',
            name='pattern_pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
