# Generated by Django 5.0.4 on 2024-04-11 12:31

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0012_rename_difficulity_level_pattern_difficulty_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='likes',
        ),
        migrations.AlterField(
            model_name='pattern',
            name='pattern_pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='pattern'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='pattern.pattern')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
