# Generated by Django 5.0.4 on 2024-04-11 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0014_pattern_likes_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='pattern_pdf',
        ),
    ]
