# Generated by Django 5.0.4 on 2024-04-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userprofile',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
