# Generated by Django 5.0.4 on 2024-04-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='difficulity_level',
            new_name='experience_level',
        ),
    ]
